apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: mtls
resources:
  - namespace.yml
  - deployment.yml
  - service.yml
  - ingress.yml
  - pvc.yml
generatorOptions:
  disableNameSuffixHash: true
configMapGenerator:
  - name: mtls
    files:
      - ./files/config.ini
  - name: mtls-admin-seeds
    files: []
  - name: mtls-user-seeds
    files: []
secretGenerator:
  - name: mtls-certs
    type: Opaque
    files:
      - ./secrets/ca.crt
      - ./secrets/ca.key
images:
  - name: drgrove/mtls-server
    newTag: v0.19.0
    digest: sha256:eb66f949f0f29ba90e1d6014f08d049feb79b33d1954055d398e7566f0ba2bf4
