from setuptools import setup, find_packages

desc = "A short-lived certificate tool based on the Zero Trust network mode"

setup(
    name="mtls-server",
    author="Danny Grove <danny@drgrovellc.com>",
    url="https://github.com/drGrove/mtls-server",
    description=desc,
    long_description=open("README.md").read(),
    long_description_content_type="text/markdown",
    project_urls={
        "Homepage": "https://github.com/drGrove/mtls-server",
        "Source": "https://github.com/drGrove/mtls-server",
        "Tracker": "https://github.com/drGrove/mtls-server/issues",
    },
    classifiers=[
        "Development Status :: 4 - Beta",
        "Intended Audience :: Developers",
        "Intended Audience :: System Administrators",
        "License :: OSI Approved :: Apache Software License",
        "Operating System :: OS Independent",
        "Topic :: Internet",
        "Topic :: Security :: Cryptography",
        "Topic :: Security",
        "Topic :: Software Development :: Libraries :: Python Modules",
        "Programming Language :: Python :: 3",
        "Programming Language :: Python :: 3.6",
        "Programming Language :: Python :: 3 :: Only",
    ],
    python_requires=">=3.6",
    setup_requires=["setuptools_scm"],
    use_scm_version=True,
    packages=find_packages(exclude=["test"]),
    entry_points={"console_scripts": ["mtlsd = mtls_server.wsgi:app"]},
    install_requires=[
        "asn1crypto",
        "cffi",
        "click",
        "cryptography",
        "flask",
        "idna",
        "itsdangerous",
        "jinja2",
        "markupsafe",
        "psycopg2-binary",
        "pycparser",
        "python-gnupg",
        "six",
        "uwsgi",
        "werkzeug",
    ],
    zip_safe=True,
)
