apiVersion: apps/v1
kind: Deployment
metadata:
  name: mtls
spec:
  template:
    spec:
      shareProcessNamespace: true
      serviceAccountName: mtls
      containers:
        - name: mtls
          volumeMounts:
            - name: sc-user-keys-volume
              mountPath: /tmp/seeds/user
            - name: sc-admin-keys-volume
              mountPath: /tmp/seeds/admin
            - name: gnupg-user
              mountPath: /home/mtls/secrets/gnupg/
            - name: gnupg-admin
              mountPath: /home/mtls/secrets/admin_gnupg/
        - name: mtls-init-user-keys
          image: kiwigrid/k8s-sidecar:1.14.2
          env:
            - name: LABEL
              value: mtls_user_key
            - name: FOLDER
              value: /tmp/user_keys
            - name: SCRIPT
              value: /tmp/restart-mtls.sh
            - name: GNUPGHOME
              value: /tmp/gnupg_home/gnupg
          volumeMounts:
            - name: sc-user-keys-volume
              mountPath: /tmp/user_keys
            - name: mtls-restart-script
              mountPath: /tmp/restart-mtls.sh
              subPath: "restart-mtls.sh"
              readOnly: true
            - name: gnupg-user
              mountPath: /tmp/gnupg_home
        - name: mtls-init-admin-keys
          image: kiwigrid/k8s-sidecar:1.14.2
          env:
            - name: LABEL
              value: mtls_admin_key
            - name: FOLDER
              value: /tmp/admin_keys
            - name: SCRIPT
              value: /tmp/restart-mtls.sh
            - name: GNUPGHOME
              value: /tmp/gnupg_home/admin_gnupg
          volumeMounts:
            - name: sc-admin-keys-volume
              mountPath: /tmp/admin_keys
            - name: mtls-restart-script
              mountPath: /tmp/restart-mtls.sh
              subPath: "restart-mtls.sh"
              readOnly: true
            - name: gnupg-admin
              mountPath: /tmp/gnupg_home
      volumes:
        - name: sc-user-keys-volume
          emptyDir: {}
        - name: sc-admin-keys-volume
          emptyDir: {}
        - name: gnupg-user
          emptyDir: {}
        - name: gnupg-admin
          emptyDir: {}
        - name: mtls-restart-script
          configMap:
            name: mtls-restart-script
            defaultMode: 0777
