apiVersion: apps/v1
kind: Deployment
metadata:
  name: mtls
spec:
  template:
    spec:
      containers:
        - name: mtls
          volumeMounts:
            - $patch: delete
              mountPath: /home/mtls/secrets/gnupg/
            - $patch: delete
              mountPath: /home/mtls/secrets/admin_gnupg/
