#! /usr/bin/env python3
import os
import sys

# Check if within pipenv, otherwise bail
if os.getenv('PIPENV_ACTIVE') != '1' and os.getenv('CI') is None:
    print('Script must be run within pipenv. Use `make create-ca`')
    sys.exit(1)

sys.path.extend([
    os.path.join(os.path.dirname(os.path.realpath(__file__)), '..')
])

from mtls_server.cert_processor import CertProcessor
from mtls_server.config import Config

CONFIG_PATH = os.path.abspath(
    os.path.join(
        os.path.dirname(__file__),
        '..',
        'config.ini'
    )
)
Config.init_config(CONFIG_PATH)
cert_processor = CertProcessor(Config)

key = cert_processor.get_ca_key()
cert_processor.get_ca_cert(key)
